### PR TITLE
Simplified installation and examples

### PR DESCRIPTION
**Pull request by ghost**
- Added Installation using Conda.
- Used pytorch-nightly to fix the backwards-compatible issue, since torchvision +0.5 requires pytorch 1.4 which is still not released. [Vision issue](https://github.com/pytorch/vision/issues/1675)
- Added predict.sh
- Simplified training and predicting workflow.

### CODE REVIEW

**Comment by WenmuZhou** [comment]
thanks for you works and there are some som ideas 
1. config_file in predict.bash is not used, so you can remove it and  add a model_path config to predict.py and predict.sh
2. move train.txt and test.txt to .dataset folder
3. Do we really need a dataset directory here?

**Comment by ghost** [comment]
1. Done
2. Done
3. Yes, I think it's better here

**Comment by WenmuZhou** [comment]
I think using train.txt and test.txt is enough, pictures and gt files can be placed anywhere

**Comment by WenmuZhou** [comment]
can you privide a mode and test img

**Comment by ghost** [comment]
That is true, but in my opinion it is better to simplify this repository for the new users, so that everything seems simple and straightforward. I am sure that the coders wont find it difficult to change the dataset directory. Also, having a datasets directory makes it easy to generate the `train.txt` and `test.txt` lists using simple commands like [generate_lists.sh](https://github.com/WenmuZhou/DBNet.pytorch/pull/10/files)

**Pull request merged**
